def get_map():
    return ["root", "BS_Root"], \
           ["pelvis", "BS_Hips"], \
           ["thigh_l", "BS_LHip"], \
           ["calf_l", "BS_LKnee"], \
           ["foot_l", "BS_LAnkle"], \
           ["toe_l", "BS_LFoot"], \
           ["thigh_r", "BS_RHip"], \
           ["calf_r", "BS_RKnee"], \
           ["foot_r", "BS_RAnkle"], \
           ["toe_r", "BS_RFoot"], \
           ["spine_01", "BS_Spine1"], \
           ["spine_02", "BS_Spine2"], \
           ["spine_03", "BS_Chest"], \
           ["neck", "BS_Neck"], \
           ["head", "BS_Head"], \
           ["lower_jaw", "BS_Jaw"], \
           ["tongue_01", "BS_Tongue01"], \
           ["tongue_02", "BS_Tongue02"], \
           ["eye_l", "BS_EyeBall_L"], \
           ["eye_r", "BS_EyeBall_R"], \
           ["clavicle_l", "BS_Clavicle_L"], \
           ["upperarm_l", "BS_LUpperArm"], \
           ["forearm_l", "BS_LLowerArm"], \
           ["forearm_twist_l", "BS_LWrist"], \
           ["hand_l", "BS_LHand"], \
           ["clavicle_r", "BS_Clavicle_R"], \
           ["upperarm_r", "BS_RUpperArm"], \
           ["forearm_r", "BS_RLowerArm"], \
           ["forearm_twist_r", "BS_RWrist"], \
           ["hand_r", "BS_RHand"], \
           ["index_01_l", "BS_LFingerA0"], \
           ["index_02_l", "BS_LFingerA1"], \
           ["index_03_l", "BS_LFingerA2"], \
           ["middle_01_l", "BS_LFingerB0"], \
           ["middle_02_l", "BS_LFingerB1"], \
           ["middle_03_l", "BS_LFingerB2"], \
           ["ring_01_l", "BS_LFingerC0"], \
           ["ring_02_l", "BS_LFingerC1"], \
           ["ring_03_l", "BS_LFingerC2"], \
           ["pinky_01_l", "BS_LFingerD0"], \
           ["pinky_02_l", "BS_LFingerD1"], \
           ["pinky_03_l", "BS_LFingerD2"], \
           ["thumb_01_l", "BS_LThumb0"], \
           ["thumb_02_l", "BS_LThumb1"], \
           ["thumb_03_l", "BS_LThumb2"], \
           ["index_01_r", "BS_RFingerA0"], \
           ["index_02_r", "BS_RFingerA1"], \
           ["index_03_r", "BS_RFingerA2"], \
           ["middle_01_r", "BS_RFingerB0"], \
           ["middle_02_r", "BS_RFingerB1"], \
           ["middle_03_r", "BS_RFingerB2"], \
           ["ring_01_r", "BS_RFingerC0"], \
           ["ring_02_r", "BS_RFingerC1"], \
           ["ring_03_r", "BS_RFingerC2"], \
           ["pinky_01_r", "BS_RFingerD0"], \
           ["pinky_02_r", "BS_RFingerD1"], \
           ["pinky_03_r", "BS_RFingerD2"], \
           ["thumb_01_r", "BS_RThumb0"], \
           ["thumb_02_r ", "BS_RThumb1"],\
           ["thumb_03_r ", "BS_RThumb2"],
